version: "3.5"

services:
  bot_db:
    container_name: bot_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=bot_db
    image: postgres:16.2-alpine3.19
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d bot_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always

  bot:
    build: ./bot
    restart: always
    depends_on:
      bot_db:
        condition: service_healthy
